/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.gui.estoque.dao;

import com.gui.estoque.util.ConnectionFactory;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Guilherme
 */
public class FornecedorDAO {
    
    public static void criarTabelaFornecedor() throws SQLException{
        try(Connection conexao = ConnectionFactory.getConnection();
                Statement stmt = conexao.createStatement()){
            
            StringBuilder createTable = new StringBuilder();

            createTable.append("CREATE TABLE IF NOT EXISTS tb_fornecedor ");
            createTable.append("(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ");
            createTable.append("nome VARCHAR(255), ");
            createTable.append("telefone VARCHAR(11), ");
            createTable.append("cnpj VARCHAR(13) ");
            createTable.append(");");

            stmt.execute(createTable.toString());
       }
    }
    
}
