/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.gui.estoque.dao;

import com.gui.estoque.util.ConnectionFactory;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Guilherme
 */
public class ProdutoDAO {
    
    public static void criarTabelaProduto() throws SQLException{
        try(Connection conexao = ConnectionFactory.getConnection();
                Statement stmt = conexao.createStatement()){
            
            StringBuilder createTable = new StringBuilder();

            createTable.append("CREATE TABLE IF NOT EXISTS tb_produto ");
            createTable.append("(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ");
            createTable.append("descricao VARCHAR(255), ");
            createTable.append("valor_compra DECIMAL(10,2), ");
            createTable.append("valor_venda DECIMAL(10,2), ");
            createTable.append("quantidade INT, ");
            createTable.append("fornecedor_id INT, ");
            createTable.append("categoria_id INT, ");
            createTable.append("FOREIGN KEY (fornecedor_id) REFERENCES tb_fornecedor(id), ");
            createTable.append("FOREIGN KEY (categoria_id) REFERENCES tb_categoria(id) ");  
            createTable.append(");");

            stmt.execute(createTable.toString());
       }
    }
}
