/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.estoque.view;

import com.gui.estoque.dao.FornecedorDAO;
import com.gui.estoque.model.FornecedorModel;
import com.gui.estoque.util.FornecedorUtil;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class f_cadastrar_fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form f_cadastrar_fornecedor
     */
    public f_cadastrar_fornecedor() {
        initComponents();
        this.setLocationRelativeTo(null);
        bt_atualizar_fornecedor.setVisible(false);
        bt_cancelar.setVisible(false);
        txt_nome_fornecedor.setEnabled(false);
        txt_telefone_fornecedor.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nome_fornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_telefone_fornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_cnpj_fornecedor = new javax.swing.JTextField();
        bt_atualizar_fornecedor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Telefone:");

        jLabel3.setText("Cnpj:");

        txt_cnpj_fornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cnpj_fornecedorFocusGained(evt);
            }
        });
        txt_cnpj_fornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_cnpj_fornecedorMouseClicked(evt);
            }
        });
        txt_cnpj_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnpj_fornecedorActionPerformed(evt);
            }
        });

        bt_atualizar_fornecedor.setText("Atualizar");
        bt_atualizar_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizar_fornecedorActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefone_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cnpj_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nome_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bt_cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_atualizar_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_cnpj_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nome_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_telefone_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_atualizar_fornecedor)
                    .addComponent(bt_cancelar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cnpj = txt_cnpj_fornecedor.getText().trim();
        String nome = txt_nome_fornecedor.getText().trim();
        String telefone = txt_telefone_fornecedor.getText().trim();
        
        if(cnpj.isEmpty()){
            JOptionPane.showMessageDialog(null, "CNPJ não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        if(nome.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nome não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        if(telefone.isEmpty()){
            JOptionPane.showMessageDialog(null, "Telefone não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        FornecedorModel fornecedor = FornecedorUtil.criarFornecedorModel(cnpj, nome, telefone);
        
        try {
            FornecedorDAO.salvarFornecedor(fornecedor);
            txt_cnpj_fornecedor.setText("");
            txt_nome_fornecedor.setText("");
            txt_telefone_fornecedor.setText("");
            txt_nome_fornecedor.setEnabled(false);
            txt_telefone_fornecedor.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(f_cadastrar_fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_cnpj_fornecedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cnpj_fornecedorFocusGained

    }//GEN-LAST:event_txt_cnpj_fornecedorFocusGained

    private void txt_cnpj_fornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_cnpj_fornecedorMouseClicked
        if(bt_atualizar_fornecedor.isVisible()){
            txt_cnpj_fornecedor.setEditable(false);
        }
    }//GEN-LAST:event_txt_cnpj_fornecedorMouseClicked

    private void txt_cnpj_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnpj_fornecedorActionPerformed
        
        String cnpj = txt_cnpj_fornecedor.getText().trim();
        
        try {
            FornecedorModel fornecedor = FornecedorDAO.buscarFornecedorPorCnpj(cnpj);
            
            if(fornecedor.getId() == null){
                txt_nome_fornecedor.setEnabled(true);
                txt_telefone_fornecedor.setEnabled(true);
                jButton2.setEnabled(true);
            }else{
                txt_cnpj_fornecedor.setEditable(false);
                txt_nome_fornecedor.setEnabled(true);
                txt_telefone_fornecedor.setEnabled(true);
                txt_nome_fornecedor.setText(fornecedor.getNome());
                txt_telefone_fornecedor.setText(fornecedor.getTelefone());
                bt_atualizar_fornecedor.setVisible(true);
                bt_cancelar.setVisible(true);
                jButton2.setEnabled(false);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(f_cadastrar_fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_cnpj_fornecedorActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        txt_cnpj_fornecedor.setEditable(true);
        txt_nome_fornecedor.setText("");
        txt_telefone_fornecedor.setText("");
        txt_nome_fornecedor.setEnabled(false);
        txt_telefone_fornecedor.setEnabled(false);
        bt_atualizar_fornecedor.setVisible(false);
        bt_cancelar.setVisible(false);
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_atualizar_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizar_fornecedorActionPerformed
        String cnpj = txt_cnpj_fornecedor.getText().trim();
        String nome = txt_nome_fornecedor.getText().trim();
        String telefone = txt_telefone_fornecedor.getText().trim();
        
        if(nome.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nome não pode ser vazio!",
                            "Aviso", JOptionPane.INFORMATION_MESSAGE); 
            return;
        }
        
        if(telefone.isEmpty()){
            JOptionPane.showMessageDialog(null, "Telefone não pode ser vazio!",
                            "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        
        try {
            FornecedorDAO.atualizarFornecedor(cnpj, nome, telefone);
            txt_cnpj_fornecedor.setText("");
            txt_cnpj_fornecedor.setEditable(true);
            txt_nome_fornecedor.setText("");
            txt_telefone_fornecedor.setText("");
            txt_nome_fornecedor.setEnabled(false);
            txt_telefone_fornecedor.setEnabled(false);
            bt_atualizar_fornecedor.setVisible(false);
            bt_cancelar.setVisible(false);
            jButton2.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(f_cadastrar_fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bt_atualizar_fornecedorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_cadastrar_fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_cadastrar_fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_cadastrar_fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_cadastrar_fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_cadastrar_fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizar_fornecedor;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_cnpj_fornecedor;
    private javax.swing.JTextField txt_nome_fornecedor;
    private javax.swing.JTextField txt_telefone_fornecedor;
    // End of variables declaration//GEN-END:variables
}
