/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.estoque.view;

import com.gui.estoque.dao.CategoriaDAO;
import com.gui.estoque.model.CategoriaModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class f_cadastro_categoria extends javax.swing.JFrame {

    /**
     * Creates new form f_cadastro_categoria
     */
    public f_cadastro_categoria() {
        initComponents();
        setLocationRelativeTo(null);
        txt_categoria_att.setEnabled(false);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cadastro_categoria = new javax.swing.JLabel();
        txt_categoria_cadastro = new javax.swing.JTextField();
        bt_save_cadastro_categoria = new javax.swing.JButton();
        bt_voltar_cadastro_categoria = new javax.swing.JButton();
        txt_categoria_att = new javax.swing.JTextField();
        bt_atualizar_categoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_cadastro_categoria.setText("Categoria:");

        txt_categoria_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoria_cadastroActionPerformed(evt);
            }
        });
        txt_categoria_cadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_categoria_cadastroKeyPressed(evt);
            }
        });

        bt_save_cadastro_categoria.setText("Salvar");
        bt_save_cadastro_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_save_cadastro_categoriaActionPerformed(evt);
            }
        });

        bt_voltar_cadastro_categoria.setText("Voltar");
        bt_voltar_cadastro_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltar_cadastro_categoriaActionPerformed(evt);
            }
        });

        bt_atualizar_categoria.setText("Atualizar");
        bt_atualizar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizar_categoriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Atualizar Categoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_categoria_att, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_atualizar_categoria))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_cadastro_categoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_categoria_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_voltar_cadastro_categoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_save_cadastro_categoria)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastro_categoria)
                    .addComponent(txt_categoria_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_categoria_att, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_atualizar_categoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_voltar_cadastro_categoria)
                    .addComponent(bt_save_cadastro_categoria))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_save_cadastro_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_save_cadastro_categoriaActionPerformed
        
        String categoria = txt_categoria_cadastro.getText().trim();
        
        if(categoria.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nome não pode ser vazio",
                            "Falha", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        CategoriaModel categoriaModel = new CategoriaModel();
        categoriaModel.setCategoria(categoria);
        
        try {
            CategoriaDAO.adicionarCategoria(categoriaModel);
        } catch (SQLException ex) {
            Logger.getLogger(f_cadastro_categoria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bt_save_cadastro_categoriaActionPerformed

    private void bt_voltar_cadastro_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltar_cadastro_categoriaActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_voltar_cadastro_categoriaActionPerformed

    private void txt_categoria_cadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_categoria_cadastroKeyPressed
        
    }//GEN-LAST:event_txt_categoria_cadastroKeyPressed

    private void txt_categoria_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoria_cadastroActionPerformed
        try {
            String categoria = CategoriaDAO.buscarCategoria(txt_categoria_cadastro.getText().trim());
            
            if(categoria.isEmpty()){
                txt_categoria_att.setText("");
               return; 
            }
            txt_categoria_att.setEnabled(true);
            txt_categoria_att.setText(categoria.toUpperCase());
            txt_categoria_cadastro.setEditable(false);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(f_cadastro_categoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_categoria_cadastroActionPerformed

    private void bt_atualizar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizar_categoriaActionPerformed
        String novo_nome_categoria = txt_categoria_att.getText().trim();
        String antigo_nome = txt_categoria_cadastro.getText().trim();
        if(!novo_nome_categoria.isEmpty()){
            if(!novo_nome_categoria.equalsIgnoreCase(txt_categoria_cadastro.getText())){
            try {
                CategoriaDAO.atualizarCategoria(antigo_nome ,novo_nome_categoria);
                txt_categoria_cadastro.setText(novo_nome_categoria);
                txt_categoria_cadastro.setEditable(true);
                txt_categoria_att.setEnabled(false);
            } catch (SQLException ex) {
                Logger.getLogger(f_cadastro_categoria.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
              JOptionPane.showMessageDialog(null, "O nome é o mesmo, para atualizar coloque um novo nome",
                            "Falha", JOptionPane.INFORMATION_MESSAGE);
            }   
        }else{
            JOptionPane.showMessageDialog(null, "O novo nome não pode ser vazio!",
                            "Falha", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
        
        
       
        
    }//GEN-LAST:event_bt_atualizar_categoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_cadastro_categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_cadastro_categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_cadastro_categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_cadastro_categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_cadastro_categoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizar_categoria;
    private javax.swing.JButton bt_save_cadastro_categoria;
    private javax.swing.JButton bt_voltar_cadastro_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cadastro_categoria;
    private javax.swing.JTextField txt_categoria_att;
    private javax.swing.JTextField txt_categoria_cadastro;
    // End of variables declaration//GEN-END:variables
}
