/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.estoque.view;

import com.gui.estoque.dao.CategoriaDAO;
import com.gui.estoque.dao.FornecedorDAO;
import com.gui.estoque.dao.ProdutoDAO;
import com.gui.estoque.model.ProdutoModel;
import com.gui.estoque.util.ProdutoUtil;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class f_cadastro_produto extends javax.swing.JFrame {

    /**
     * Creates new form f_cadastro_produto
     */
    public f_cadastro_produto() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        FornecedorDAO.buscarTodosFornecedores().forEach(f -> cb_fornecedor_cadastro.addItem(f.getNome()));
        CategoriaDAO.buscarCategorias().forEach(cb_categoria_cadastro::addItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_descricao_cadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_valorCompra_cadastro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValorVenda_cadastro_produto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_quantidade_cadastroProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cb_fornecedor_cadastro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb_categoria_cadastro = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_salvar_cadastro_produto = new javax.swing.JButton();
        bt_voltar_cadastro_produto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Descrição:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Valor de compra:");

        txt_valorCompra_cadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_valorCompra_cadastroFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Valor venda:");

        txtValorVenda_cadastro_produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorVenda_cadastro_produtoFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Quantidade:");

        txt_quantidade_cadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantidade_cadastroProdutoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fornecedor:");

        cb_fornecedor_cadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o fornecedor" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Categoria:");

        cb_categoria_cadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha sua categoria" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Codigo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_fornecedor_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_valorCompra_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorVenda_cadastro_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_categoria_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_descricao_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_quantidade_cadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_descricao_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_quantidade_cadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_valorCompra_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtValorVenda_cadastro_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_fornecedor_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cb_categoria_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Cadastro de produtos");

        bt_salvar_cadastro_produto.setBackground(new java.awt.Color(0, 255, 51));
        bt_salvar_cadastro_produto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_salvar_cadastro_produto.setText("Salvar");
        bt_salvar_cadastro_produto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bt_salvar_cadastro_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvar_cadastro_produtoActionPerformed(evt);
            }
        });

        bt_voltar_cadastro_produto.setBackground(new java.awt.Color(255, 51, 51));
        bt_voltar_cadastro_produto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_voltar_cadastro_produto.setText("Voltar");
        bt_voltar_cadastro_produto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bt_voltar_cadastro_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_salvar_cadastro_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvar_cadastro_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_voltar_cadastro_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_quantidade_cadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantidade_cadastroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantidade_cadastroProdutoActionPerformed

    private void bt_salvar_cadastro_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvar_cadastro_produtoActionPerformed
        
        String descricao = txt_descricao_cadastro.getText();
        String quantidade = txt_quantidade_cadastroProduto.getText();
        String valor_compra = txt_valorCompra_cadastro.getText();
        String valor_venda = txtValorVenda_cadastro_produto.getText();
        String fornecedor = cb_fornecedor_cadastro.getSelectedItem().toString();
        String categoria = cb_categoria_cadastro.getSelectedItem().toString();
        
        
        
        if(descricao.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nome não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        if(quantidade.isEmpty()){
            JOptionPane.showMessageDialog(null, "Quantidade não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
        if(valor_compra.isEmpty()){
            JOptionPane.showMessageDialog(null, "Valor de compra não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
         if(valor_venda.isEmpty()){
            JOptionPane.showMessageDialog(null, "Valor de venda não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
         
          if(fornecedor.isEmpty()){
            JOptionPane.showMessageDialog(null, "Fornecedor não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        
           if(categoria.isEmpty()){
            JOptionPane.showMessageDialog(null, "Categoria não pode ser vazio!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
        }
           
        ProdutoModel produto;
        try {
            produto = ProdutoUtil.criarProdutoModel(descricao, valor_compra,
                    valor_venda, quantidade, fornecedor, categoria);
            
            ProdutoDAO.adicionarProduto(produto);
            
            txt_descricao_cadastro.setText("");
            txtValorVenda_cadastro_produto.setText("");
            txt_valorCompra_cadastro.setText("");
            txt_quantidade_cadastroProduto.setText("");
            cb_categoria_cadastro.setSelectedIndex(0);
            cb_fornecedor_cadastro.setSelectedIndex(0);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(f_cadastro_produto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_salvar_cadastro_produtoActionPerformed

    private void txt_valorCompra_cadastroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_valorCompra_cadastroFocusLost
        String valor = txt_valorCompra_cadastro.getText();
        
        if(valor.contains(",")){
            JOptionPane.showMessageDialog(null, "Digite o valor com Ponto ' . '!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
            txt_valorCompra_cadastro.setText("");
        }
        
        
    }//GEN-LAST:event_txt_valorCompra_cadastroFocusLost

    private void txtValorVenda_cadastro_produtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorVenda_cadastro_produtoFocusLost
        String valor = txtValorVenda_cadastro_produto.getText();
        
        if(valor.contains(",")){
            JOptionPane.showMessageDialog(null, "Digite o valor com Ponto ' . '!",
                            "Aviso", JOptionPane.WARNING_MESSAGE);
            txtValorVenda_cadastro_produto.setText("");
        }
        
    }//GEN-LAST:event_txtValorVenda_cadastro_produtoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_cadastro_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_cadastro_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_cadastro_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_cadastro_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new f_cadastro_produto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(f_cadastro_produto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_salvar_cadastro_produto;
    private javax.swing.JButton bt_voltar_cadastro_produto;
    private javax.swing.JComboBox<String> cb_categoria_cadastro;
    private javax.swing.JComboBox<String> cb_fornecedor_cadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtValorVenda_cadastro_produto;
    private javax.swing.JTextField txt_descricao_cadastro;
    private javax.swing.JTextField txt_quantidade_cadastroProduto;
    private javax.swing.JTextField txt_valorCompra_cadastro;
    // End of variables declaration//GEN-END:variables
}
