/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.estoque.view;

import com.gui.estoque.dao.FornecedorDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class f_deletar_fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form f_deletar_fornecedor
     */
    public f_deletar_fornecedor() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        FornecedorDAO.buscarTodosFornecedores().forEach(cb_deletar_fornecedor::addItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_deletar_fornecedor = new javax.swing.JComboBox<>();
        bt_deletar_fornecedor = new javax.swing.JButton();
        bt_voltar_deletar_fornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fornecedor:");

        cb_deletar_fornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um fornecedor" }));

        bt_deletar_fornecedor.setText("Deletar");
        bt_deletar_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletar_fornecedorActionPerformed(evt);
            }
        });

        bt_voltar_deletar_fornecedor.setText("Voltar");
        bt_voltar_deletar_fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltar_deletar_fornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_deletar_fornecedor, 0, 180, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_voltar_deletar_fornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_deletar_fornecedor)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_deletar_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_deletar_fornecedor)
                    .addComponent(bt_voltar_deletar_fornecedor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deletar_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletar_fornecedorActionPerformed

        var nomeFornecedor = cb_deletar_fornecedor.getSelectedItem();
        
        if(nomeFornecedor == null || nomeFornecedor.toString().equalsIgnoreCase("Escolha um fornecedor")){
          JOptionPane.showMessageDialog(null, "Nome não pode ser vazio!",
                            "Falha", JOptionPane.ERROR_MESSAGE); 
          return;
        }
        try {
            FornecedorDAO.deletarFornecedor(nomeFornecedor.toString().trim());
            cb_deletar_fornecedor.removeAllItems();
            FornecedorDAO.buscarTodosFornecedores().forEach(cb_deletar_fornecedor::addItem);
        } catch (SQLException ex) {
            Logger.getLogger(f_deletar_fornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_deletar_fornecedorActionPerformed

    private void bt_voltar_deletar_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltar_deletar_fornecedorActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_voltar_deletar_fornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_deletar_fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_deletar_fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_deletar_fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_deletar_fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new f_deletar_fornecedor().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(f_deletar_fornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_deletar_fornecedor;
    private javax.swing.JButton bt_voltar_deletar_fornecedor;
    private javax.swing.JComboBox<String> cb_deletar_fornecedor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
