/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.estoque.view;

import com.gui.estoque.dao.FornecedorDAO;
import com.gui.estoque.model.FornecedorModel;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme
 */
public class f_listar_forncedores extends javax.swing.JFrame {

    /**
     * Creates new form f_listar_forncedores
     */
    public f_listar_forncedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nome_buscar_func = new javax.swing.JTextField();
        bt_buscar_fornecedores = new javax.swing.JButton();
        scrol_panel_del_func = new javax.swing.JScrollPane();
        table_buscar_fornecedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        bt_buscar_fornecedores.setText("Buscar");
        bt_buscar_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscar_fornecedoresActionPerformed(evt);
            }
        });

        scrol_panel_del_func.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrol_panel_del_funcMouseClicked(evt);
            }
        });

        table_buscar_fornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "TELEFONE", "CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_buscar_fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_buscar_fornecedoresMouseClicked(evt);
            }
        });
        scrol_panel_del_func.setViewportView(table_buscar_fornecedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrol_panel_del_func, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nome_buscar_func, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_buscar_fornecedores)
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nome_buscar_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscar_fornecedores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrol_panel_del_func, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_buscar_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscar_fornecedoresActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) table_buscar_fornecedores.getModel();
        modelo.setRowCount(0);
        
        String nome = txt_nome_buscar_func.getText();
        
        List<FornecedorModel> fornecedores;
                
        if(nome.isEmpty()){
            try {
                fornecedores = FornecedorDAO.buscarTodosFornecedores();
                fornecedores.forEach(f -> modelo.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getTelefone(),
                    f.getCnpj()
                }));
            } catch (SQLException ex) {
                Logger.getLogger(f_listar_forncedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try{
                fornecedores = FornecedorDAO.buscarFornecedorPorContainNome(nome);
                fornecedores.forEach(f -> modelo.addRow(new Object[]{
                    f.getId(),
                    f.getNome(),
                    f.getTelefone(),
                    f.getCnpj()
                }));
            } catch (SQLException ex) {
                Logger.getLogger(f_listar_forncedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_bt_buscar_fornecedoresActionPerformed

    private void scrol_panel_del_funcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrol_panel_del_funcMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scrol_panel_del_funcMouseClicked

    private void table_buscar_fornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_buscar_fornecedoresMouseClicked
        if (evt.getClickCount() == 2) {
        int linha = table_buscar_fornecedores.getSelectedRow();
        if (linha != -1) {
            // Pega o ID (assumindo que está na primeira coluna)
            int idFornecedor = (int) table_buscar_fornecedores.getValueAt(linha, 0);
            
            
            try {
                // Chama a outra tela, passando o ID
                f_deletar_fornecedor deletarForne = new f_deletar_fornecedor(idFornecedor);
                deletarForne.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(f_listar_forncedores.class.getName()).log(Level.SEVERE, null, ex);
            }
            // Fecha essa tela, se desejar
            this.dispose(); 
        }
    }
    }//GEN-LAST:event_table_buscar_fornecedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_listar_forncedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_listar_forncedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_listar_forncedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_listar_forncedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_listar_forncedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar_fornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrol_panel_del_func;
    private javax.swing.JTable table_buscar_fornecedores;
    private javax.swing.JTextField txt_nome_buscar_func;
    // End of variables declaration//GEN-END:variables
}
