/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.estoque.view;

import com.gui.estoque.util.ConnectionFactory;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Guilherme
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_categoria = new javax.swing.JMenu();
        add_categoria = new javax.swing.JMenuItem();
        remove_categoria = new javax.swing.JMenuItem();
        att_categoria = new javax.swing.JMenuItem();
        menu_fornecedor = new javax.swing.JMenu();
        menu_produto = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_categoria.setText("Categoria");
        menu_categoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        add_categoria.setText("Adicionar categoria");
        add_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_categoriaActionPerformed(evt);
            }
        });
        menu_categoria.add(add_categoria);

        remove_categoria.setText("Remover categoria");
        remove_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_categoriaActionPerformed(evt);
            }
        });
        menu_categoria.add(remove_categoria);

        att_categoria.setText("Atualizar categoria");
        menu_categoria.add(att_categoria);

        jMenuBar1.add(menu_categoria);

        menu_fornecedor.setText("Fornecedor");
        jMenuBar1.add(menu_fornecedor);

        menu_produto.setText("Produto");
        jMenuBar1.add(menu_produto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_categoriaActionPerformed
        f_cadastro_categoria cadastro_categoria = new f_cadastro_categoria();
        cadastro_categoria.setVisible(true);
    }//GEN-LAST:event_add_categoriaActionPerformed

    private void remove_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_categoriaActionPerformed
        try {
            f_deletar_categoria deletarCategoria = new f_deletar_categoria();
            deletarCategoria.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_remove_categoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    ConnectionFactory.criarTodasTabelas();
                } catch (SQLException ex) {
                    Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem add_categoria;
    private javax.swing.JMenuItem att_categoria;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_categoria;
    private javax.swing.JMenu menu_fornecedor;
    private javax.swing.JMenu menu_produto;
    private javax.swing.JMenuItem remove_categoria;
    // End of variables declaration//GEN-END:variables
}
